version: '3'
services:
  jobmanager-service:
    container_name: jobmanager
    build: .
    image: registry.atosresearch.eu:18484/jobmanager-service:dev
    ports: 
      - 8082:8082 # Forward the exposed port 8081 on the container to port 8081 on the host machine
    environment: 
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DRIVER=mysql
      - SERVER_PORT=${SERVER_PORT}
    restart: on-failure
    depends_on:
      # - postgres # This service depends on postgres. Start that first.
      - mysql # This service depends on mysql. Start that first.
    networks:
      - server

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --default-authentication-plugin=sha256_password
    # command: "--default-authentication-plugin=mysql_native_password --ignore-db-dir=lost+found --innodb_use_native_aio=0"
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DATABASE_HOST=${DB_HOST} 
    restart: unless-stopped
    volumes:
      - ./data_mysql:/var/lib/mysql
      - ./db_init/:/docker-entrypoint-initdb.d
    networks:
      - server

# Networks to be created to facilitate communication between containers
networks:
  server:
